version: "3"

services:
  ms_users_app:
    container_name: ms_orders_app
    restart: unless-stopped
    build:
      context: ../
      dockerfile: docker/app/local.Dockerfile
    environment:
      - APP_ENV=dev
      - LANG=fr_FR.UTF-8
      - PORT=3000
    env_file:
      - app/.env
    ports:
      - 3000:3000
    volumes:
      - "../app:/home/app"
      - "./app/.env:/home/app/.env"
      - "/home/app/node_modules"
    networks:
      - app-network

  ms-users_db:
    image: postgres
    container_name: ms_orders_db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_PORT=5432
    volumes:
      - db_ms_orders_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_ms_orders_data:

networks:
  app-network:
    driver: bridge